const STOPWORDS=new Set('的 了 與 和 或 是 在 有 我 你 他 她 它 們 一個 以及 這個 那個 如何 可以 透過 關於 來源 年的 皮膚 多少 知多少 問題 症狀 常見 使用 文章 內文'.split(' '));
const DOMAIN_TERMS=['食物過敏','過敏原','免疫系統','IgE','非IgE','過敏性休克','蕁麻疹','血管性水腫','呼吸困難','營養','蛋白質','膳食纖維','全穀雜糧','蔬果','血糖','早餐','中高齡','高齡健康','肌少症','骨質疏鬆','糖尿病','高血壓','腸胃道','健康管理','臨床營養'];
function stripHtml(s=''){return String(s).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&[^;]+;/g,' ').replace(/\[來源\d+(?:,\s*\d+)*\]/g,' ').replace(/\s+/g,' ').trim()}
function summary(post){const given=stripHtml(post.excerpt||'');if(given.length>=24)return truncate(given,86);const text=stripHtml(post.body||'');const sentence=(text.match(/[^。！？!?]{24,120}[。！？!?]/)||[text.slice(0,110)])[0];return truncate(sentence,86)}
function keywords(post){if(Array.isArray(post.keywords)&&post.keywords.length)return post.keywords.slice(0,5);const text=[post.title,post.excerpt,stripHtml(post.body)].join(' ');const found=[];for(const term of DOMAIN_TERMS){if(text.toLowerCase().includes(term.toLowerCase()))found.push(term)}const headings=[...(post.body||'').matchAll(/<h[2-3][^>]*>(.*?)<\/h[2-3]>/gi)].map(m=>stripHtml(m[1])).filter(Boolean);const titleParts=String(post.title||'').replace(/[？?！!]/g,'').split(/[：:、，,\s-]+/).filter(w=>w.length>=2&&w.length<=8);const words=(stripHtml(text).match(/[\u4e00-\u9fa5]{2,6}|[A-Za-z][A-Za-z-]{2,}/g)||[]).filter(w=>!STOPWORDS.has(w)&&!/來源|\d/.test(w));const score=new Map();[...found,...headings,...titleParts,...words].forEach((w,i)=>{const key=w.trim();if(!key||STOPWORDS.has(key))return;score.set(key,(score.get(key)||0)+(i<found.length?6:1))});return [...score.entries()].sort((a,b)=>b[1]-a[1]||a[0].length-b[0].length).slice(0,5).map(([w])=>w)}
function truncate(text,max){return text.length>max?`${text.slice(0,max-1)}…`:text}
function homeImageSrc(post){if(!post.image)return'blog/images/default.svg';if(/^https?:\/\//.test(post.image)||post.image.startsWith('/'))return post.image;if(post.image.startsWith('blog/'))return post.image;if(post.image.startsWith('images/'))return `blog/${post.image}`;return `blog/images/${post.image}`}
function postCard(post){return `<a class="home-post-card" href="blog/post.html?id=${encodeURIComponent(post.id)}"><img src="${homeImageSrc(post)}" alt=""><div class="home-post-body"><div class="post-meta">${post.date}</div><h3>${post.title}</h3><p>${summary(post)}</p><div class="keywords">${keywords(post).map(k=>`<span>${k}</span>`).join('')}</div></div></a>`}
async function loadHomePosts(){const host=document.querySelector('#home-posts');if(!host)return;try{const res=await fetch('blog/posts.json',{cache:'no-store'});const posts=(await res.json()).posts||[];const selected=posts.filter(post=>post.showOnHome===true).slice(0,4);host.innerHTML=selected.map(postCard).join('')||'<p>尚未選擇首頁文章。請到 Admin 勾選「顯示在首頁」。</p>'}catch(e){host.innerHTML='<p>文章載入失敗，請稍後再試。</p>'}}loadHomePosts();
